version: '3'
services:
  agent:
    image: portainer/agent
    restart: always
    environment:
      AGENT_CLUSTER_ADDR: {{ ansible_hostname }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001