#- block:
#    - name: Set docker-compose version
#      shell: curl --silent "https://api.github.com/repos/docker/compose/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/';
#      register: docker_compose_version
#    - name: Ensure docker-compose is installed and available
#      get_url:
#        url : https://github.com/docker/compose/releases/download/{{ docker_compose_version.stdout }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
#        dest: /usr/local/bin/docker-compose
#        mode: '+x'
#  when: ansible_os_family == "Debian"
#  become: true

- name: Install python package
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-pip
    update_cache: yes  
  become: yes

- name: Install docker python package
  pip:
    name:
      - docker
      - docker-compose
  become: yes

- name: create application network
  docker_network:
    name: application
